"""add target fields to audit log

Revision ID: 174017a74210
Revises: e4e577080fc2
Create Date: 2024-11-29 15:26:47.902976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174017a74210'
down_revision = 'e4e577080fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_failed_login_count')
        batch_op.drop_column('new_login_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_login_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('new_failed_login_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
