"""Add login tracking fields with server defaults

Revision ID: e4e577080fc2
Revises: e5d102788b45
Create Date: 2024-11-29 14:58:57.222989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e577080fc2'
down_revision = 'e5d102788b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the temporary table if it exists
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_user')
    
    # Update existing rows to have default values
    op.execute('UPDATE user SET login_count = 0 WHERE login_count IS NULL')
    op.execute('UPDATE user SET failed_login_count = 0 WHERE failed_login_count IS NULL')
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('login_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.alter_column('failed_login_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('failed_login_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)
        batch_op.alter_column('login_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)

    # ### end Alembic commands ###
